/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#ffffff",
        "surface-dim": "#ffffff",
        "on-tertiary-fixed": "#000000",
        "surface-bright": "#f3f4f6",
        "border-subtle": "#d1d5db",
        "on-surface-variant": "#111111",
        "glass-fill": "rgba(255, 255, 255, 0.03)",
        background: "#ffffff",
        error: "#ffb4ab",
        surface: "#f8fafc",
        "on-tertiary-fixed-variant": "#46474a",
        "primary-container": "#000000",
        "surface-container-high": "#f3f4f6",
        "tertiary-container": "#e3e2e6",
        "inverse-surface": "#e5e2e1",
        "on-primary-fixed": "#1a1c1c",
        "glow-cyan": "rgba(0, 255, 242, 0.15)",
        primary: "#000000",
        "charcoal-surface": "#141414",
        "tertiary-fixed-dim": "#c7c6ca",
        "outline-variant": "#444748",
        "inverse-primary": "#5d5f5f",
        "surface-container-highest": "#353534",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed-variant": "#494740",
        "on-tertiary": "#2f3034",
        "on-primary-fixed-variant": "#454747",
        "secondary-container": "#494740",
        "on-secondary": "#32302a",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#636565",
        "primary-fixed-dim": "#c6c6c7",
        "on-error": "#690005",
        "on-background": "#000000",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed-dim": "#cbc6bd",
        "surface-tint": "#c6c6c7",
        "surface-container": "#201f1f",
        "on-secondary-container": "#b9b5ac",
        "secondary-fixed": "#e7e2d9",
        outline: "#8e9192",
        "tertiary-fixed": "#e3e2e6",
        "primary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#1d1c16",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-container": "#646468",
        "on-primary": "#2f3131",
        secondary: "#cbc6bd",
        "error-container": "#93000a",
        "on-surface": "#000000",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "element-gap": "32px",
        "section-gap": "120px",
        gutter: "24px",
        "grid-margin": "64px",
        unit: "8px",
      },
      fontFamily: {
        "display-xl": ["EB Garamond"],
        "display-lg": ["EB Garamond"],
        "meta-tag": ["JetBrains Mono"],
        "label-mono": ["JetBrains Mono"],
        "headline-xl": ["EB Garamond"],
        "headline-xl-mobile": ["EB Garamond"],
        "body-md": ["Space Grotesk"],
        "body-lg": ["Space Grotesk"],
      },
      fontSize: {
        "display-xl": ["120px", { lineHeight: "110px", letterSpacing: "-0.04em", fontWeight: "500" }],
        "display-lg": ["80px", { lineHeight: "84px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "meta-tag": ["10px", { lineHeight: "12px", fontWeight: "700" }],
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-xl": ["48px", { lineHeight: "56px", fontWeight: "400" }],
        "headline-xl-mobile": ["32px", { lineHeight: "38px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
